# Local dev profile: use with docker-compose-dev.yml (PostgreSQL only). No Keycloak.
# Activate with: spring.profiles.active=local
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
